### ISSUE TITLE
[Bug] Cats are spawning around regardless of non-conditional cat spawning

### ISSUE THREAD

**Issue by Wpgradford** [Xipit/cats-expanded#3]
I've tried turning non-conditional cat spawning on and off, neither seems to impact the random cats spawning in my base lol. The mod is incredible otherwise though, it's really cute!

**Comment by Xipit** [comment]
Hi Wpgradford, nice to hear you are enjoying the mod :).
What Version are you using?
How long did you play with it disabled that you were still seeing cats spawn?

ty for bringing this issue up!

**Comment by Wpgradford** [comment]
I'm using Cats Expanded 1.0.0 for Fabric version 1.18.2. I'm not sure how long it takes for a cat to spawn, I'll start a new world and keep my eye out for when the first one spawns

**Comment by Xipit** [comment]
Hi, sry for seemingly abandoning this issue. 
Development has shifted to 1.19.0 and last time i tested it while working on 1.18.2 it worked correctly for me.
If you find any other issues feel free to mention them here.
